apps/front/models.py
from exts import db
from werkzeug.security import generate_password_hash,check_password_hash
import shortuuid,enum
from datetime import datetime
class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4
class FrontUser(db.Model):
    __tablename__='frontuser'
    id = db.Column(db.String(100),primary_key=True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11),nullable=False,unique=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50),unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100)) #头像
    signature = db.Column(db.String(100)) #签名
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)

    def __init__(self,*args,**kwargs):
        if 'password'in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(FrontUser,self).__init__(*args,**kwargs)


    @property
    def password(self):
        return self._password

    @password.setter
    def password(self,newped):
        self._password = generate_password_hash(newped)

    def check_password(self,rawpwd):
        return check_password_hash(self._password,rawpwd)

apps/front/forms.py
from ..forms import BoseForm
from wtforms import StringField,IntegerField
from wtforms.validators import Regexp,EqualTo,ValidationError,InputRequired
from tool import zzcache

class SignupForm(BoseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}',message='请输入正确格式的手机号码')])
    sms_captcha = StringField(validators=[Regexp(r'\w{4}',message='请输入正确格式的短信验证码')])
    username = StringField(validators=[Regexp(r'.{2,20}',message='请输入正确格式的用户名')])
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}',message='请输入正确格式的密码')])
    password2 = StringField(validators=[EqualTo('password1',message='两次密码输入不一致')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='请输入正确格式的验证码')])

    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data
        if sms_captcha != '1111': #测试代码
            #从memecache中取验证码
            sms_captcha_mem = zzcache.get(telephone)
            if not sms_captcha_mem or sms_captcha.lower() != sms_captcha_mem.lower():
                super(SignupForm, self).get_error()
                raise ValidationError(message='短信验证码错误！')
    def validate_graph_captcha(self,field):
        graph_captcha = field.data
        if graph_captcha != '1111':  # 测试代码
            graph_captcha_mem = zzcache.get(graph_captcha.lower())
            if not graph_captcha_mem:
                super(SignupForm, self).get_error()
                raise ValidationError(message='图形验证码错误！')


class SigninForm(BoseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message='请输入正确格式的手机号码')])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确格式的密码')])
    remember = StringField()


class AddPostForm(BoseForm):
    title = StringField(validators=[InputRequired(message='请传入标题！')])
    content = StringField(validators=[InputRequired(message='请传入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请传入板块id!')])

class AddCommentForm(BoseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])

class PraiseForm(BoseForm):
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])
    fuser_id = StringField(validators=[InputRequired(message='请传入用户id！')])

class CancelPraiseForm(BoseForm):
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])
    fuser_id = StringField(validators=[InputRequired(message='请传入用户id！')])

apps/common/views.py
from flask import Blueprint,request,make_response,jsonify
from tool.dysms_python import demo_sms_send
from tool import restful,zzcache
from tool.captcha import Captcha
from .forms import SMSCaptchaForm
from io import BytesIO #专门写二进制流数据
import json,qiniu
bp = Blueprint("common",__name__,url_prefix='/c')

@bp.route('/')
def index():
    return 'common index'

#   get请求不安全，别人轻易可以调用你的接口
# @bp.route('/sms_captcha/')
# def sms_captcha():
#     telephone = request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message='请传入手机号码')
#     captcha = Captcha.gene_text(4)
#     params = json.dumps({'code': captcha}) #将 Python 对象编码成 JSON 字符串
#     print(params)
#     result = demo_sms_send.send_sms(telephone,params)
#     print(type(result))
#     resu=str(result,encoding='utf-8') #bytes转字符串
#     print(resu)
#     params2 = json.loads(resu) #JSON到字典转化
#     # print(params['Code'])
#     if params2['Code'] == 'OK':
#         return restful.success()
#     else:
#         return restful.params_error(message='短信验证码发送失败')
@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate() == 1:
        return restful.params_error(message='号码已存在！')
    if form.validate() == 2:
        telephone = form.telephone.data
        captcha = Captcha.gene_text(4)
        params = json.dumps({'code': captcha})  # 将 Python 对象编码成 JSON 字符串
        print(params)
        result = demo_sms_send.send_sms(telephone,params) #发送验证码
        print(type(result))
        resu=str(result,encoding='utf-8') #bytes转字符串
        print(resu)
        params2 = json.loads(resu) #JSON到字典转化
        if params2['Code'] == 'OK':
            zzcache.set(telephone, captcha) #将验证码存入memcache
            return restful.success()
        else:
            # zzcache.set(telephone, captcha)  # 将验证码存入memcache
            return restful.params_error(message='短信验证码发送失败')
    else:
        return restful.params_error(message='参数错误！！！')

@bp.route('/captcha/')
def graph_captcha():
    #获取验证码
    image,text = Captcha.gene_captcha()
    zzcache.set(text.lower(),text.lower(),120)
    print(text)
    #BytesIO 创建字节流对象
    out = BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'#指定response对象内容类型
    return resp

#上传七牛图片接口
@bp.route('/uptoken/')
def uptoken():
    access_key = 'VUqezRGdo0N_78MAn3DS5bO7n2uNI7E86OiGz8Df'
    secret_key = 'fiuQZzcWWplmEb_0kW3IcyH5jjN6nXb6Opz19zB5'
    q = qiniu.Auth(access_key,secret_key)
    bucket = 'banners'
    token = q.upload_token(bucket)
    return jsonify({'uptoken':token})

apps/front/__init__.py
from .views import bp
from . import hooks

apps/front/views.py
from flask import Blueprint,views,render_template,request,url_for,session,g,redirect,abort
from .forms import SignupForm,SigninForm,AddPostForm,AddCommentForm,PraiseForm,CancelPraiseForm
from tool import restful,safetool
from .models import FrontUser
from ..models import BannerModel,BoardModel,PostModel,CommentModel,HighlightPostModel,PraiseModel
from exts import db
from .decorators import login_required
from flask_paginate import Pagination,get_page_parameter
from sqlalchemy.sql import func

import config

bp = Blueprint("front",__name__)

@bp.route('/')
def index():
    board_id = request.args.get('bd',type=int,default=None)#从前端拿到模版id
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(3)
    boards = BoardModel.query.all()
    sort = request.args.get("st",type=int,default=1)
    page = request.args.get(get_page_parameter(),type=int,default=1)#指定当前是第几页,默认显示第一页
    start = (page-1)*config.PER_PAGE #每一页开始位置
    end = start+config.PER_PAGE #每一页结束位置
    posts = None
    total = 0
    # 排序方式
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        #按照加精的时间倒序排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).\
            order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    elif sort == 3:
        #按照点赞数量排序
        query_obj = PostModel.query.order_by(PostModel.praise_count.desc())
    elif sort == 4:
        #按照评论数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).\
            order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())


    if board_id: #如果有则显示相应模版下的帖子
        query_obj = query_obj.filter(PostModel.board_id==board_id)
        posts = query_obj.slice(start,end)
        total = query_obj.count()
    else:
        posts = query_obj.order_by(PostModel.id.desc()).slice(start,end)
        total = query_obj.count()
    pagination = Pagination( bs_version=3,page=page,total=total,outer_window=0)
    context ={
        'banners':banners,
        'boards':boards,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort
    }
    # print('+++++++++++++')
    # print(type(banners))
    # print('+++++++++++++')
    return render_template('front/front_index.html',**context)

#发布帖子接口
@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
               return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title,content=content,board_id=board_id)
            post.author = g.Front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())

#注销登录
@bp.route('/logout/')
@login_required
def logout():
    del session[config.FRONT_USER_ID]
    return redirect(url_for('front.signin'))


#帖子详情视图
@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if config.FRONT_USER_ID in session:
        fuser_id = g.Front_user.id
        praise = PraiseModel.query.filter_by(fuser_id=fuser_id).first()
        context = {
            'post': post,
            'praise': praise
        }
        return render_template('front/front_pdatail.html', **context)
    else:
        if not post:
            abort(404)
        context={
            'post': post
        }
        return render_template('front/front_pdatail.html',**context)


#添加评论
@bp.route('/acomment/',methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        post_id = form.post_id.data
        content = form.content.data
        post = PostModel.query.filter_by(id=post_id)
        if post:
            comment = CommentModel(content=content,post_id=post_id)
            comment.author = g.Front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这篇帖子')
    else:
        return restful.params_error(message=form.get_error())


#点赞
@bp.route('/praise/',methods=['POST'])
@login_required
def user_praise():
    form = PraiseForm(request.form)
    if form.validate():
        post_id = form.post_id.data
        fuser_id = form.fuser_id.data
        post = PostModel.query.filter_by(id=post_id).first()
        fuser = FrontUser.query.filter_by(id=fuser_id).first()

        if post and fuser:
            praise_pid = PraiseModel.query.filter_by(post_id=post_id).first()
            praise_uid = PraiseModel.query.filter_by(fuser_id=fuser_id).first()
            if praise_pid and praise_uid:
                return restful.params_error(message="用户重复点赞!")
            else:
                config.PRAISW_COUNT = config.PRAISW_COUNT + 1
                now_praise = PraiseModel(fuser_id=fuser_id,post_id=post_id)
                post.praise_count = config.PRAISW_COUNT
                db.session.add(now_praise)
                db.session.commit()
                return restful.success()
        else:
            return restful.params_error(message="帖子或用户不存在")
    else:
        return restful.params_error(message=form.get_error())

#取消点赞
@bp.route('/c_praise/',methods=['POST'])
@login_required
def cancelpraise():
    form = PraiseForm(request.form)
    if form.validate():
        post_id = form.post_id.data
        fuser_id = form.fuser_id.data
        praise = PraiseModel.query.filter_by(post_id=post_id).first()
        post = PostModel.query.filter_by(id=post_id).first()
        if praise:
            count = post.praise_count - 1
            post.praise_count = count
            db.session.delete(praise)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message="没有这篇帖子！")
    else:
        return restful.params_error(message=form.get_error())




class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer #获取上一个页面的url
        if return_to and return_to != request.url and safetool.is_safe_url(return_to):
            return render_template('front/front_signup.html',return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password1 = form.password1.data
            user = FrontUser(telephone=telephone,username=username,password=password1)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            # message = form.get_error().popitem()[1][0]
            message = form.get_error()
            print(form.get_error())
            return restful.params_error(message=message)


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safetool.is_safe_url(return_to)and url_for('front.signup'):
            return render_template('front/front_signin.html',return_to=return_to)
        else:
            return render_template('front/front_signin.html')
    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机或密码错误！')
        else:
            return restful.params_error(form.get_error())

bp.add_url_rule('/signup/',view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/',view_func=SigninView.as_view('signin'))

templates/front/front_404.html
{% from "commom/macros.html " import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
    <style>
        html,body,div,p,form,label,ul,li,dl,dt,dd,ol,img,button,h1,h2,h3,h4,h5,h6,b,em,strong,small{margin:0;padding:0;border:0;list-style:none;font-style:normal;font-weight:normal;}
         body{
            background: #e8f5fd;
              }
        .lost{
            {#position: absolute;top:50%;left: 50%;margin-top: -20px;margin-left: -20px;#}
            position:absolute; /*绝对定位*/
            top:50%; /*距顶部50%*/
            left:50%;
            margin:-100px 0 0 -150px; /*设定这个div的margin-top的负值为自身的高度的一半,margin-left的值也是自身的宽度的一半的负值.(感觉在绕口令)*/
            width:300px; /*宽为400,那么margin-top为-200px*/
            height:200px; /*高为200那么margin-left为-100px;*/
            z-index:99; /*浮动在最上层 */
        }
        .lost a{
            margin-left: 60%;
            text-decoration:none
        }
    </style>
</head>
<body>
    <div class="lost">
        <img src="{{ static("images/404.png") }}" alt="">
        <a href="/">点击跳转到首页</a>
    </div>
</body>
</html>

templates/front/front_apost.html
{% from 'commom/macros.html' import static %}
{% extends "front/front_base.html" %}
{% block title %}发布帖子{% endblock %}

{% block head %}
    <script src="{{ static("ueditor/ueditor.config.js") }}"></script>
    <script src="{{ static("ueditor/ueditor.all.min.js") }}"></script>
    <script src="{{ static('front/js/front_apost.js') }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select class="form-control" name="board_id">
              {% if boards %}
                  {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                  {% endfor %}
              {% else %}
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
              {% endif %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height: 500px"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

templates/front/front_base.html
{% from "commom/macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "commom/_heads.html" %}
    <link rel="stylesheet" href="{{ static("front/css/front_base.css") }}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head -%}
    {%- endblock %}

</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ZZ区块链论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入关键字">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if g.Front_user %}
                    <span id="login-tag" data-is-login="1" style="display: none"></span>
                    <li class="dropdown">

                      <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
                        <img src="{{ g.Front_user.avatar or static('images/1.png/') }}" alt="" style="width: 30px;height: 30px;border-radius: 50%;margin-bottom: -7px;
    margin-right: 2px;">
                        {{ g.Front_user.username }}
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#" data-toggle="modal" data-target="#myModal">个人中心</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="{{ url_for('front.logout') }}">注销</a></li>
                      </ul>
                    </li>
              {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
              {% endif %}

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
      {% block body%}{% endblock %}
    </div>

<!-- Modal -->
    {% if g.Front_user %}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">个人中心</h4>
          </div>
          <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-3">用户名：</label>
                    <span class="col-sm-3">{{ g.Front_user.username }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">手机号码：</label>
                    <span class="col-sm-3">{{ g.Front_user.telephone }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">邮箱：</label>
                    <span class="col-sm-3">{{ g.Front_user.email if g.Front_user.email else '用户未设置' }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">真实姓名：</label>
                    <span class="col-sm-3">{{ g.Front_user.realname if g.Front_user.realname else '用户未设置' }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">签名：</label>
                    <span class="col-sm-3">{{ g.Front_user.signature if g.Front_user.signature else '用户未设置' }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">性别：</label>
                    <span class="col-sm-3">{{ g.Front_user.gender if g.Front_user.gender else '用户未设置' }}</span>
                </div>
                <div class="form-group">
                    <label class="col-sm-3">加入时间：</label>
                    <span class="col-sm-4">{{ g.Front_user.join_time  }}</span>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
     </div>
    {% endif %}

</body>
</html>

templates/front/front_common.html
{% from 'commom/macros.html' import static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
{#    <link rel="stylesheet" href="sweetalert2/dist/sweetalert2.min.css" type="text/css">#}
    <link href="{{ static("common/sweetalert2.min.css") }}" rel="stylesheet">
    <script src="{{ static("common/sweetalert2.all.min.js") }}"></script>

    <script src="{{ static("common/zzajax.js") }}"></script>
    <script src="{{ static('common/param.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css') }}">
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="{{ static('images/7.jpg') }}" alt="">
            </a>
        </div>
        <h2 class="b-signup">{% block h2_block %}{% endblock %}</h2>
        <div class="bbox">
            {% block signinbox %}
            
            {% endblock %}
        </div>
        <span style="display: none" id="return_to">{{ return_to }}</span>
    </div>
</body>
</html>

templates/front/front_index.html
{% from 'commom/macros.html' import static%}
{% extends "front/front_base.html" %}
{% block title %}ZZ区块链论坛{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
    <script src="{{ static("front/js/index.js") }}"></script>
{% endblock %}
{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
          <!-- 指示器 -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- 轮播图 -->
          <div class="carousel-inner" role="listbox">
              {% for banner in banners %}
                  {% if loop.first %}
                    <div class="item active">
                  {% else %}
                    <div class="item ">
                  {% endif %}
                        <a href="{{ banner.link_url }} " target="_blank">
                            <img src="{{ banner.image_b }}" alt="..." class="img-b">
                        </a>
                    </div>
              {% endfor %}

              
          </div>

          <!-- 左右切换的控制按钮 -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="post-group">
            <ul class="post-group-head subnav">
                <li class="ac"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖</a></li>
                <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
            </ul>
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="author-avatar-group">
                            <img src="{{ post.author.avatar or url_for('static',filename='images/1.png/') }}" alt="">
                        </div>
                        <div class="post-info-group">
                            <p class="post-title">
                                <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                                {% if post.highlight %}
                                    <span class="label label-danger">精华帖</span>
                                {% endif %}
                                </p>
                            <p class="post-info">
                                <span>作者:{{ post.author.username }}</span>
                                <span>发布时间:{{ post.create_time }}</span>
                                <span>评论:0</span>
                                <span>阅读:0</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div style="text-align: center;">
                {{ pagination.links }}
            </div>

        </div>
    </div>
    <div class="sm-container">
        <div style="margin-bottom: 10px">
            <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布新帖</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item ">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}

            {% for board in boards %}
                {% if board.id == current_board %}
                     <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
                {% else %}
                     <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}

            {% endfor %}

        </div>
    </div>

{% endblock %}