apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash

#权限
class CMSpermission(object):
    #通过二进制方式来表示 1111 1111
    #权限全开
    ALL_PERMISSION = 0b11111111
    #1.访问者权限
    VISITOR = 0b00000001
    #2.管理帖子权限
    POSTER = 0b00000010
    #轮播图权限
    BANNER = 0b00000011
    #3.管理评论的权限
    COMMENTER = 0b00000100
    #4.管理板块的权限
    MODERATOR = 0b00001000
    #5.管理前台用户权限
    FRONTUSER = 0b00010000
    #6.管理后台用户权限
    CMSUSER =   0b00100000
    #7.开发者
    ADMINER =   0b01000000

cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id',db.Integer,db.ForeignKey('cms_role.id'),primary_key=True),
    db.Column('cms_user_id',db.Integer,db.ForeignKey('cms_user.id'),primary_key=True)
)


class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50),nullable=False)
    desc = db.Column(db.String(200),nullable=True)
    create_time = db.Column(db.DateTime,default=datetime.now)
    permissions = db.Column(db.Integer,default=CMSpermission.VISITOR)
    users = db.relationship('CMSUser',secondary=cms_role_user,backref='roles')

class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100),nullable=False)
    email = db.Column(db.String(50),nullable=False,unique=True)
    join_time = db.Column(db.DateTime,default=datetime.now)
    #重写构造函数，因为在命令行设置时只要password，没有_password
    def __init__(self,username,password,email):
        self.username = username
        self.password = password
        self.email = email

    #在数据库中显示加密后的密码
    @property
    def password(self):
        return self._password
    @password.setter
    def password(self,rew_password):
        self._password=generate_password_hash(rew_password)

    def check_password(self,rew_password):
        result = check_password_hash(self._password,rew_password)
        return result

    #获取用户所有权限
    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            all_permissions |= permissions
        return all_permissions

    #判断用户是否具有相应的权限
    def has_permission(self,permission):
        all_permissions = self.permissions #直接调用上面permission还是获取用户拥有的权限
        result = all_permissions & permission == permission
        return result

    #判断用户是否是开发者
    @property
    def is_developer(self):
        return self.has_permission(CMSpermission.ALL_PERMISSION)

apps/cms/forms.py
# 表单验证
from wtforms import StringField,IntegerField,ValidationError
from wtforms.validators import Email,InputRequired,Length,EqualTo
from ..forms import BoseForm
from tool import zzcache
from flask import g

class LoginForm(BoseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式'),InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6,20,message='请输入正确的密码格式')])
    remember = IntegerField()
class ResetpwdForm(BoseForm):
    newpwd = StringField(validators=[Length(6,20,message='请输入正确格式的新密码')])
    oldpwd = StringField(validators=[Length(6,20,message='请输入正确格式的旧密码')])
    newpwd2 = StringField(validators=[EqualTo('newpwd',message="两次密码不一致")])

class ResetemailForm(BoseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式')])
    captcha = StringField(validators=[Length(6,6,message='验证码格式错误')])
    #当执行captcha表单验证时同时也会执行validate_captcha函数来验证
    def validate_captcha(self,field):
        captcha = field.data
        email = self.email.data
        captcha_cache = zzcache.get(email) #从memcached中获取email所对应的验证码
        if not captcha_cache or captcha.lower() != captcha_cache.lower():
            raise ValidationError('邮箱验证码错误！')
    def validate_email(self,field):
        email = field.data
        user = g.cms_user #通过g对象来获取数据库中用户原邮箱名
        if user.email == email:
            raise ValidationError('新邮箱不能和旧邮箱相同')

class AbannerForm(BoseForm):
    name = StringField(validators=[InputRequired(message='请输入轮播图名称！')])
    image_b = StringField(validators=[InputRequired(message='请输入轮播图图片链接！')])
    link_url = StringField(validators=[InputRequired(message='请输入轮播图跳转链接！')])
    priority = IntegerField(validators=[InputRequired(message='请输入轮播图优先级！')])

class UbannerForm(AbannerForm):
    banner_id = IntegerField(validators=[InputRequired(message='请输入轮播图的id!')])


class AddBoardForm(BoseForm):
    name = StringField(validators=[InputRequired(message='请输入板块名')])


class UpdateBoardForm(AddBoardForm):
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id')])

class DeleteBoardForm(UpdateBoardForm):
    pass

apps/cms/__init__.py
from .views import bp
from .models import CMSUser,CMSRole,CMSpermission
from .hooks import before_request

apps/cms/views.py
from flask import Blueprint,views,render_template,request,session,redirect,url_for,g
from .forms import (
    LoginForm,
    ResetpwdForm,
    ResetemailForm,
    AbannerForm,
    UbannerForm,
    AddBoardForm,
    UpdateBoardForm,
    DeleteBoardForm
)
from flask_paginate import Pagination,get_page_parameter
from .models import CMSUser,CMSpermission
from ..models import BannerModel,BoardModel,PostModel,HighlightPostModel
from .decorators import login_required,permission_required
from exts import db,mail
from tool import restful,zzcache
from flask_mail import Message #封装电子邮件消息
from tasks import send_mail
import config,string,random
bp = Blueprint("cms",__name__,url_prefix='/cms')

@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')
#登录视图函数
class LoginView(views.MethodView):
    def get(self,message=None):
        return render_template('cms/cms_login.html',message=message)
    def post(self):
        # 表单验证
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    #如果设置了session.permanent =True
                    #过期时间为31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或者密码错误')
        else:
            message = form.get_error()
            return self.get(message=message)

#通过查询字符串方式获取用户所传的邮箱地址（/email_captcha/?email=xxx@qq.com）
@bp.route('/email_captcha/')
def email_captcha():
    email = request.args.get('email')
    if not email:
        return restful.params_error('请传递邮箱参数')
    #给用户输入的邮箱发送验证码
    source= list(string.hexdigits) #生成0-9 a-f A-F字符串且转换为列表
    captcha ="".join(random.sample(source,6))
    # message = Message("ZZ论坛邮箱验证码",recipients=[email],body="您的验证码是:%s"%captcha)
    #异常处理
    # try:
    #     mail.send(message)
    # except:
    #     return restful.server_error()
    try:
        send_mail.delay("ZZ论坛邮箱验证码",[email],"您的验证码是:%s"%captcha)
    except:
        return restful.server_error()

    #讲邮箱和验证码缓存到memcached中
    zzcache.set(email,captcha)
    return restful.success()

@bp.route('/email/')
def send_email():
    message = Message('测试邮件',recipients=['15111390080@163.com'],body='快点找工作了啦！！！')
    mail.send(message)
    return 'success'


#注销登录
@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))
#个人信息界面
@bp.route('/percenter/')
@login_required
def percenter():
    return render_template('cms/cms_percenter.html')
#更改密码
class Change_pwd(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_changepwd.html')
    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
              user.password = newpwd
              db.session.commit()
              return restful.success()
            else:
                return restful.params_error("旧密码错误")
        else:
            messagr = form.get_error()
            # print("+++++++++++")
            # print(messagr)
            # print("+++++++++++")

            return restful.params_error(messagr)
# 修改邮箱
class Resetemail(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/resetemail.html')
    def post(self):
        form = ResetemailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())

#帖子
@bp.route('/posts/')
@login_required
@permission_required(CMSpermission.POSTER)
def posts():
    # 帖子分页
    page = request.args.get(get_page_parameter(), type=int, default=1)  # 指定当前是第几页,默认显示第一页
    start = (page - 1) * config.PER_PAGE  # 每一页开始位置
    end = start + config.PER_PAGE  # 每一页结束位置
    posts_p = PostModel.query.order_by(PostModel.id.desc()).slice(start, end)
    total = PostModel.query.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0)
    context = {
        'posts': posts_p,
        'pagination':pagination
    }
    return render_template('cms/cms_posts.html',**context)

#移除帖子
@bp.route('/dposts/',methods=['POST'])
@login_required
@permission_required(CMSpermission.POSTER)
def dposts():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error(message='请传入帖子id!')
    # post = PostModel.query.filter_by(id=post_id).first()
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error(message='没有这篇帖子！')
    db.session.delete(post)
    db.session.commit()
    return restful.success()

@bp.route('/comments/')
@login_required
@permission_required(CMSpermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')

# 板块
@bp.route('/boards/')
@login_required
@permission_required(CMSpermission.MODERATOR)
def boards():
    board_moldes = BoardModel.query.all()
    context={
        'boards': board_moldes
    }
    return render_template('cms/cms_boards.html',**context)


@bp.route('/fusers/')
@login_required
@permission_required(CMSpermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


@bp.route('/cusers/')
@login_required
@permission_required(CMSpermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@login_required
@permission_required(CMSpermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


#轮播图管理界面
@bp.route('/banners/')
@login_required
@permission_required(CMSpermission.BANNER)
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html',banners=banners)


#添加轮播图
@bp.route('/abanner/',methods=['POST'])
@login_required
@permission_required(CMSpermission.BANNER)
def abanner():
    form = AbannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_b = form.image_b.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name,image_b=image_b,link_url=link_url,priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


#更新轮播图
@bp.route('/ubanner/',methods=['POST'])
@login_required
@permission_required(CMSpermission.BANNER)
def ubanner():
    form = UbannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_b = form.image_b.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner_id = form.banner_id.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_b = image_b
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message="没有这个轮播图!")
    else:
        return restful.params_error(message=form.get_error())


#删除轮播图
@bp.route('/dbanner/',methods=['POST'])
@login_required
@permission_required(CMSpermission.BANNER)
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请传入轮播图Id!')
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个轮播图！')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()

# 添加板块
@bp.route('/aboard/',methods=['POST'])
@login_required
@permission_required(CMSpermission.MODERATOR)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())

#更新板块
@bp.route('/uboard/',methods=['POST'])
@login_required
@permission_required(CMSpermission.MODERATOR)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board_id = form.board_id.data
        board = BoardModel.query.filter_by(id=board_id).first()
        if board:
            # print(board.name)
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块！')
    else:
        return restful.params_error(message=form.get_error())


#删除板块
@bp.route('/dboard/',methods=['POST'])
@login_required
@permission_required(CMSpermission.MODERATOR)
def dboard():
    form = DeleteBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        board = BoardModel.query.filter_by(id=board_id).first()
        if board:
            db.session.delete(board)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块')
    else:
        return restful.params_error(message=form.get_error())

#帖子加精接口
@bp.route('/hpost/',methods=['POST'])
@login_required
@permission_required(CMSpermission.POSTER)
def hpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error('请传入帖子id!')
    post = PostModel.query.get(post_id)

templates/cms/cms_banners.html
{% extends "cms/cms_common.html"%}
{% from "commom/macros.html" import static %}
{% block title -%}
    轮播图管理
{%- endblock %}
{% block title_1 -%}
    首页
{%- endblock %}
{% block title_2 -%}
    {{ self.title() }}
{%- endblock %}
{% block head %}
    <script src="http://cdn.staticfile.org/plupload/2.1.1/moxie.js"></script>
    <script src="http://cdn.staticfile.org/plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-JS-SDK/1.0.14-beta/qiniu.min.js"></script>
    <script src="{{ static('common/zzqiniu.js') }}"></script>
    <script src="{{ static("cms/js/banners.js") }}"></script>
    <style>
        .top-box button{
            float: right;
        }
    </style>
{% endblock %}
{% block main_center %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered table1">
        <thead>
            <tr>
                <th>名称</th>
                <th>图片链接</th>
                <th>跳转链接</th>
                <th>优先级</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
{#                将后台轮播图数据绑定到tr标签上#}
                <tr class="success" data-name="{{ banner.name }}" data-image="{{ banner.image_b }}" data-link="{{ banner.link_url }}"
                    data-priority="{{ banner.priority }} " data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_b }}" target="_blank">{{ banner.image_b }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.creat_time }}</td>
                    <td>
                        <button class="btn-default btn-xs edit-banner-btn" >编辑</button>
                        <button class="btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


    <!-- Modal -->
    <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">轮播图</h4>
          </div>
          <div class="modal-body">
              <form action="" class="form-horizontal">
                  <div class="form-group">
                      <label class="col-sm-2 control-label">名称：</label>
                      <div class="col-sm-10">
                          <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-2 control-label">图片：</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" name="image_b" placeholder="轮播图图片">
                      </div>
                      <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-2 control-label">链接：</label>
                      <div class="col-sm-10">
                          <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                      </div>
                  </div>
                  <div class="form-group" >
                      <label class="col-sm-2 control-label">权重：</label>
                      <div class="col-sm-10">
                          <input type="number" class="form-control" name="priority" placeholder="优先级">
                      </div>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/cms/cms_boards.html
{% extends 'cms/cms_common.html' %}
{% from 'commom/macros.html' import static %}
{% block title -%}
    板块管理
{%- endblock %}
{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}
{% block title_1 -%}
    首页
{%- endblock %}
{% block title_2 -%}
    {{ self.title() }}
{%- endblock %}
{% block main_center %}
    <div class="top-box" >
        <button class="btn btn-warning" style="float: right" id="add_board-btn">添加板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>板块名称</td>
                <td>帖子数量</td>
                <td>创建时间</td>
                <td>操作</td>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr class="success" data-name="{{ board.name }}" data-id="{{ board.id }}">
                    <td>{{ board.name }}</td>
                    <td>0</td>
                    <td>{{ board.creat_time }}</td>
                    <td>
                        <button class="btn-default btn-xs edit-board-btn" >编辑</button>
                        <button class="btn-danger btn-xs delete-board-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/cms_changepwd.html
{% extends 'cms/cms_common.html' %}
{%from "commom/macros.html" import static %}
{% block title -%}
    修改密码
{%- endblock %}
{% block title_1 -%}
    首页
{%- endblock %}
{% block title_2 %}
    {{ self.title() }}
{% endblock %}
{% block head %}
{#    <style>#}
{#        .boxone{#}
{#            width: 30px;#}
{#        }#}
{#    </style>#}
    <script src="{{ static("cms/js/resetpwd.js" )}}"></script>
{% endblock %}
{% block main_center %}
    <form action="" method="post">
        <div class="boxone">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">旧密码</span>
                <input type="password" class="form-control" name="oldpwd" placeholder="输入旧密码">
            </div>
         </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">新密码</span>
                <input type="password" class="form-control" name="newpwd" placeholder="输入新密码">
            </div>
         </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">确认新密码</span>
                <input type="password" class="form-control" name="newpwd2" placeholder="请确定密码">
            </div>
         </div>
        <div class="form-group">
            <button type="button" class="btn btn-info" id="submit">立即保存</button>
        </div>
       </div>

    </form>
    
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_common.html' %}
{% block title -%}
    评论管理
{%- endblock %}
{% block title_1 -%}
    首页
{%- endblock %}
{% block title_2 -%}
    {{ self.title() }}
{%- endblock %}
{% block main_center %}
    评论管理页面
{% endblock %}

templates/cms/cms_common.html
{% from "commom/macros.html" import static%}
<!DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{#    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='cms/css/bootstrap.min.css') }}" >
{#    <script type="text/javascript" src="{{ url_for('static',filename='cms/js/jquery-1.8.3.min.js' ) }}"></script>#}
    <script type="text/javascript" src="{{ url_for('static',filename='cms/js/menu.js' ) }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='cms/css/style.css') }}" >
{#ajax对csef_token导入请求头的封装#}
    <script src="{{ static("common/zzajax.js") }}"></script>
{#    导入弹出框模版sweetalert2#}
    <script src="{{ static("common/sweetalert2.all.min.js") }}"></script>
    <script src="{{ static("common/sweetalert2.min.css") }}"></script>
    {% block head %}{% endblock %}
</head>

<body>
<div class="top"></div>
<div id="header">
	<div class="logo">***后台管理系统</div>
	<div class="navigation">
		<ul>
		 	<li>欢迎您！</li>
			<li><a href="{{ url_for('cms.percenter') }}">{{ g.cms_user.username }}</a></li>
			<li><a href="{{ url_for('cms.logout') }}">退出</a></li>
		</ul>
	</div>
</div>
<div id="content">
	<div class="left_menu">
        <ul id="nav_dot">
                <li class="index">
                 <div class="index">
                   <a href='{{ url_for('cms.index') }}' class="a1"><span class="sp"></span>首页</a>
                 </div>
                </li>

             <li id="li1">
              <h4 class="M1"><span></span>个人中心</h4>
              <div class="list-item none">
                <a href='{{ url_for('cms.percenter') }}'>个人信息</a>
                <a href='{{ url_for('cms.changepwd') }}'>修改密码</a>
                <a href='{{ url_for('cms.resetemail') }}'>修改邮箱</a>
              </div>
             </li>

            {% set cms_user = g.cms_user %}
            {% if cms_user.has_permission(CMSpermission.POSTER) %}
             <li id="li2">
                  <h4 class="M2"><span></span>帖子相关</h4>
                  <div class="list-item none">
                    <a href='{{ url_for('cms.posts') }}'>帖子管理</a>
                    <a href=''>工单处理2</a>
                   </div>
             </li>
            {% endif %}

            {% if cms_user.has_permission(CMSpermission.COMMENTER) %}
              <li id="li3">
                  <h4 class="M3"><span></span>评论相关</h4>
                  <div class="list-item none">
                    <a href='{{ url_for('cms.comments') }}'>评论管理</a>
                    <a href=''>基础教学2</a>
                  </div>
              </li>
            {% endif %}
            {% if cms_user.has_permission(CMSpermission.MODERATOR) %}
                <li id="li4">
                  <h4 class="M4"><span></span>板块相关</h4>
                  <div class="list-item none">
                    <a href='{{ url_for('cms.boards') }}'>板块管理</a>
                    <a href='{{ url_for("cms.banners") }}'>轮播图</a>
                  </div>
                </li>
            {% endif %}
            {% if cms_user.has_permission(CMSpermission.FRONTUSER) %}
             <li id="li5">
                  <h4 class="M5"><span></span>前台用户相关</h4>
                  <div class="list-item none">
                    <a href='{{ url_for('cms.fusers') }}'>前台用户管理</a>
                    <a href=''>调研问卷2</a>
                  </div>
             </li>
            {% endif %}
            {% if cms_user.has_permission(CMSpermission.CMSUSER) %}
                <li id="li6">
                      <h4  class="M6"><span></span>CMS用户相关</h4>
                      <div class="list-item none">
                        <a href='{{ url_for('cms.cusers') }}'>用户管理</a>
                        <a href=''>数据统计2</a>
                      </div>
                </li>
            {% endif %}
            {% if cms_user.has_permission(CMSpermission.ADMINER) %}
                <li id="li7">
                      <h4  class="M7"><span></span>CMS组相关</h4>
                      <div class="list-item none">
                        <a href='{{ url_for('cms.croles') }}'>组管理</a>
                        <a href=''>奖励管理2</a>
                      </div>
                </li>
            {% endif %}

{#				<li>#}
{#          <h4  class="M9"><span></span>内容管理</h4>#}
{#        </li>#}
{#				<li>#}
{#          <h4   class="M10"><span></span>系统管理</h4>#}
{#          <div class="list-item none">#}
{#            <a href=''>系统管理1</a>#}
{#            <a href=''>系统管理2</a>#}
{#            <a href=''>系统管理3</a>#}
{#          </div>#}
{#        </li>#}
        </ul>
		</div>
		<div class="m-right">
			<div class="right-nav">
					<ul>
							<li><img src="{{ url_for('static',filename='images/home.png' ) }}"></li>
								<li style="margin-left:25px;">您当前的位置：</li>
								<li><a href="{{ url_for('cms.index') }}">{% block title_1 %}{% endblock %}</a></li>
								<li>></li>
								<li><a href="#">{% block title_2 %}{% endblock %}</a></li>
						</ul>
			</div>
			<div class="main">
                {% block main_center %}{% endblock %}
			</div>
		</div>
</div>
<div class="bottom"></div>
<div id="footer"><p>Copyright©  2015 版权所有 京ICP备xxxxxx号-10</p></div>
<script>navList(12);</script>
</body>
</html>